### ISSUE TITLE
Duplicate Expected Tank Values

### ISSUE THREAD

**Issue by ljford7** [IDDT/wot-console-playerbase-analysis#1]
Hi, 

First off, this is great what you have done. I use it all the time. There are couple of small issues I have found with the expected tank values (I use the values to put in excel and do some of my own analysis). There are duplicate expected values for the tanks below.

26433	AMX CDC Black Edition	8	mediumTank
31537	T-34-3 Black Edition	8	mediumTank
31841	STA-2 Black Edition	8	mediumTank
32033	Python T7 Combat Car	2	lightTank
32273	Captured KV-1	5	heavyTank
32289	Fox T7 Combat Car	2	lightTank	usa
32513	IS-6 Black Edition	8	heavyTank
32529	Lowe Black Edition	8	heavyTank
32545	Viper T7 Combat Car	2	lightTank
33057	Kraken T7 Combat Car	2	lightTank
33297	The Hidden StuG III	5	AT-SPG
33569	Hornet T7 Combat Car	2	lightTank
34337	T34 Black Edition	8	heavyTank

The tanks below are missing expected values.

32081	Mark I	1	lightTank
T28 Concept (don't have the ID for it)

I found these by taking the ID export and the expected values export and comparing them.

I can send you the excel file with the comparison if you would like as well.

Thanks for you hard work!

[WOT.zip](https://github.com/IDDT/wot-console-playerbase-analysis/files/851104/WOT.zip)

**Comment by IDDT** [comment]
Hey,

Thank you for your feedback and sorry for the late reply. The duplicate values from the top of the message were put intentionally because I was afraid Black Editions didn't accumulate enough stats as of Jan 2017.

Colored T7s are extremely unpopular and share the same specs with normal T7. 

And KV1 / Hidden Stug were added after the data was gathered. The values were copied to them as a temporary measure until the next recalculation which is going to happen soon-ish.

As about Mark 1, the WG API was returning 0s, which I thought is normal for an event-only car.

Good find with T28, for some reason it's not there.

If you are interested, [this is the list with all the replacements](https://github.com/IDDT/wot-console-playerbase-analysis/blob/master/8_WN8_assemble.py), particularly lines 11 and 28.

**Comment by ljford7** [comment]
Thank you for the update.

Looking at 26 in your replacement list, the Captured KV-1 is different from the KV-1 and should have different expected stats.

**Comment by IDDT** [comment]
That's right, however, it's not possible to add new tanks one by one. The whole scraping and calculation process has to happen. For that reason, I think, it's sensible to use values of similar tanks and calculate new values every 4-6 months.
